### ISSUE TITLE
base64 encoded passwords breaks nova-manage

### ISSUE THREAD

**Issue by bitskri3g** [GeorgiaCyber/kinetic#7]
If a base64 encoded password in the dynamic_pillar has a '+' symbol, it will break nova manage.

```
2018-12-31 15:49:35.595 16085 ERROR nova.objects.cell_mapping [req-7d8197a5-f222-40c4-b230-1ff93f127894 - - - - -] Failed to parse [database]/connection to format cell mapping: ValueError: invalid literal for int() with base 10: 'SYYkKq4V7JhtqFDN+mrXfvhIBn1+'
2018-12-31 15:49:35.595 16085 ERROR nova.objects.cell_mapping Traceback (most recent call last):
2018-12-31 15:49:35.595 16085 ERROR nova.objects.cell_mapping   File "/usr/lib/python2.7/dist-packages/nova/objects/cell_mapping.py", line 137, in _format_db_url
2018-12-31 15:49:35.595 16085 ERROR nova.objects.cell_mapping     return CellMapping._format_url(url, CONF.database.connection)
2018-12-31 15:49:35.595 16085 ERROR nova.objects.cell_mapping   File "/usr/lib/python2.7/dist-packages/nova/objects/cell_mapping.py", line 107, in _format_url
2018-12-31 15:49:35.595 16085 ERROR nova.objects.cell_mapping     'port': default_url.port,
2018-12-31 15:49:35.595 16085 ERROR nova.objects.cell_mapping   File "/usr/lib/python2.7/urlparse.py", line 113, in port
2018-12-31 15:49:35.595 16085 ERROR nova.objects.cell_mapping     port = int(port, 10)
2018-12-31 15:49:35.595 16085 ERROR nova.objects.cell_mapping ValueError: invalid literal for int() with base 10: 'SYYkKq4V7JhtqFDN+mrXfvhIBn1+'
2018-12-31 15:49:35.595 16085 ERROR nova.objects.cell_mapping
```

Suggested fix is to have openssl continue to generate passwords until it creates one without a '+' for all cases.  Haven't had an issue with '=' yet.

**Comment by bitskri3g** [comment]
Fixed by utilizing salt.module.mod_random in lieu of shell-based solution
